version: '3'
services:
  nginx:
    image: bihela/bihela-dev3cs:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx-3cs/nginx.conf:/etc/nginx/nginx.conf:ro

  node-app:
    image: bihela/node-app:latest
    expose:
      - "3000"
    depends_on:
      - nginx
